INSERT INTO USER(EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME) VALUES ('serenaprifti@gmail.com','Serena1','Prifti','$2y$12$Kib/Huaxr.SSeLQWeiCiJ.ph3JGtY6b1MubdeCBPMVM5hItJS5Xdi
','serena1');
INSERT INTO USER(EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME) VALUES ('serenaprifti1@gmail.com','Serena2','Prifti','$2y$12$Kib/Huaxr.SSeLQWeiCiJ.ph3JGtY6b1MubdeCBPMVM5hItJS5Xdi
','serena2');
INSERT INTO USER(EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME) VALUES ('serenaprifti2@gmail.com','Serena3','Prifti','$2y$12$Kib/Huaxr.SSeLQWeiCiJ.ph3JGtY6b1MubdeCBPMVM5hItJS5Xdi
','serena3');
INSERT INTO GROUPS(GROUP_NAME,DESCRIPTION) VALUES('group1','group1 information');
INSERT INTO GROUPS(GROUP_NAME,DESCRIPTION) VALUES('group2','group2 information');
INSERT INTO GROUPS(GROUP_NAME,DESCRIPTION) VALUES('group3','group3 information');
INSERT INTO GROUPS(GROUP_NAME,DESCRIPTION) VALUES('group4','group4 information');
INSERT INTO PERMISSIONS(TITLE,DESCRIPTION) VALUES('ADMIN','Admin information');
INSERT INTO PERMISSIONS(TITLE,DESCRIPTION) VALUES('EMPLOYEES','Employee information');
