INSERT INTO USER(EMAIL,FIRST_NAME,LAST_NAME) VALUES ('serenaprifti@gmail.com','Serena1','prifti');
INSERT INTO USER(EMAIL,FIRST_NAME,LAST_NAME) VALUES ('serenaprifti@gmail.com','Serena2','prifti');
INSERT INTO USER(EMAIL,FIRST_NAME,LAST_NAME) VALUES ('serenaprifti@gmail.com','Serena3','prifti');
INSERT INTO USER(EMAIL,FIRST_NAME,LAST_NAME) VALUES ('serenaprifti@gmail.com','Serena4','prifti');
INSERT INTO USER(EMAIL,FIRST_NAME,LAST_NAME) VALUES ('serenaprifti@gmail.com','Serena5','prifti');
INSERT INTO GROUPS(GROUP_NAME) VALUES('group1');
INSERT INTO GROUPS(GROUP_NAME) VALUES('group2');
INSERT INTO GROUPS(GROUP_NAME) VALUES('group3');
INSERT INTO GROUPS(GROUP_NAME) VALUES('group4');
INSERT INTO GROUPS(GROUP_NAME) VALUES('group5');

